# Generated by Django 2.2.5 on 2019-11-02 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20190921_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactiondate',
            field=models.DateField(default=datetime.datetime(2019, 11, 2, 21, 0, 31, 152829), verbose_name='transaction date'),
        ),
    ]
